version: '2'
services:
  elasticsearch:
    ports:
        - 9200:9200
    image: elasticsearch

  kibana:
    image: kibana
    ports:
        - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    links:
      - elasticsearch

  pilot:
    image: log-pilot:latest
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/filebeat:/var/lib/filebeat
      - /var/log/filebeat:/var/log/filebeat
      - /:/host
    environment:
      LOGGING_OUTPUT: elasticsearch
      PILOT_LOG_PREFIX: "aliyun,custom"
      ELASTICSEARCH_HOSTS: elasticsearch:9200
    links:
      - elasticsearch
